export const SWITCH_LANGUAGE       = 'app/App/SWITCH_LANGUAGE';
export const INCREMENT_COUNTER     = 'app/App/INCREMENT_COUNTER';
export const TOGGLE_RIGHT_SIDEBAR  = 'app/App/TOGGLE_RIGHT_SIDEBAR';
export const SAVE_USER_INFO  = 'app/App/SAVE_USER_INFO';
export const SAVE_USER_INFO_INFLIGHT   = 'app/App/SAVE_USER_INFO_INFLIGHT';
export const SAVE_USER_INFO_SUCCESSFUL = 'app/App/SAVE_USER_INFO_SUCCESSFUL';
export const SAVE_USER_INFO_ERROR      = 'app/App/SAVE_USER_INFO_ERROR';

export const FETCH_ALL_USER_INFO  = 'app/App/FETCH_ALL_USER_INFO';
export const FETCH_ALL_USER_INFO_INFLIGHT   = 'app/App/FETCH_ALL_USER_INFO_INFLIGHT';
export const FETCH_ALL_USER_INFO_SUCCESSFUL = 'app/App/FETCH_ALL_USER_INFO_SUCCESSFUL';
export const FETCH_ALL_USER_INFO_ERROR      = 'app/App/FETCH_ALL_USER_INFO_ERROR';